## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
## Playbook Assumptions:
##

---

####################
##
## Begin postinstall 

- hosts: myBastion
  tasks:

  - name: "LIBVIRT-POSTINSTALL: check for ansible"
    shell: 
      cmd: rpm -q ansible
    ignore_errors: yes
    register: test_ansible

####################
##
## When ansible is not installed

  - block:

    - name: "LIBVIRT-POSTINSTALL: collect RHN username and password"
      pause:
        prompt: "Enter RHSM username: "
        echo: yes
      register: rhsm_username

    - pause:
        prompt: "Enter RHN password: "
        echo: no
      register: rhsm_password

    - name: "LIBVIRT-POSTINSTALL: rhsm register"
      redhat_subscription:
        state: present
        auto_attach: yes
        force_register: yes
        username: "{{ rhsm_username.user_input }}"
        password: "{{ rhsm_password.user_input }}"
  
    - name: "LIBVIRT-POSTINSTALL: enable ansible repo"
      rhsm_repository: 
        name: "{{ item }}"
        purge: True
        state: enabled
      with_items: 
        - "ansible-2.9-for-rhel-8-x86_64-rpms"
  
    - name: "LIBVIRT-POSTINSTALL: install ansible"
      yum: name=ansible state=installed
  
    - name: "LIBVIRT-POSTINSTALL: rhsm unregister"
      redhat_subscription:
        state: absent

    when: test_ansible.rc != 0

####################
##
## Continue Post-Install

  - name: "LIBVIRT-POSTINSTALL: stat project directory"
    stat: path="./RHEL8-Workshop"
    register: test_project_dir

  - name: "LIBVIRT-POSTINSTALL: clone project from github"
    shell: 
      cmd: |
        git clone -b Summit2020 http://github.com/xtophd/RHEL8-Workshop
    when: test_project_dir.stat.exists == false

  - name: "LIBVIRT-POSTINSTALL: install fresh config files"
    shell: 
      cmd: |
        cp ./RHEL8-Workshop/sample-configs/rhel8-workshop ./RHEL8-Workshop/config
    when: test_project_dir.stat.exists == false

  - name: "LIBVIRT-POSTINSTALL: deploy RHEL 8 Workshop"
    shell: 
      cmd: |
        cd /root/RHEL8-Workshop
        bash prepare-rhel8-workshop.sh
    when: test_project_dir.stat.exists == false

