- hosts: all
  tasks:
  
    - name: "TEMPLATE modify /etc/motd"
      template:
        src: motd-generic.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644  

    - name: "SERVICE disable and stop unwanted services"
      service: 
        name="{{ item.name }}"
        state=stopped
        enabled=no
      with_items:
        - {name: 'rhsmcertd'}

    - name: "CMD disable yum plugins for subscription-manager"
      shell: 
        cmd: |          
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/subscription-manager.conf
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/product-id.conf
                    
    - name: "USER create and/or reset users"
      user: name="{{ item.name }}" password="{{ item.password }}"
      with_items:
        - {name: 'root', password: '$6$D8EoJrUnZrCWxW9h$PQNdk98xj0od.IJXFtSZNhupd3USy/2WkvqIsl/d0Hbhv0myeUCbFciBUrnsOaR/Idnhi3YI5154M6dBJMafh1'}
        - {name: 'student', password: '$6$9Jk5EGiB2aBl95kj$RIdiSqNdKt95zqddStFUY/zVKIUujWfGWJkLM5KQ.7zY88Kxxa0qm78qLMFRAqDO2qOrp.qZBaQAKcUFm1Is70'}


- import_playbook: rhel8-setup-appstreams.yml
- import_playbook: rhel8-setup-firewalld.yml
- import_playbook: rhel8-setup-boom.yml
- import_playbook: rhel8-setup-webconsole.yml
- import_playbook: rhel8-setup-podman.yml
- import_playbook: rhel8-setup-stratis.yml
- import_playbook: rhel8-setup-tlog.yml
