---
- hosts: workstation.example.com
  tasks:

    - name: "SETUP VIRTUALIZATION: yum install qemu-kvm libvirt virt-install libvirt-client libguestfs-tools"
      yum: name=qemu-kvm,libvirt,virt-install,libvirt-client,libguestfs-tools,wget,cockpit-machines,lorax-composer,composer-cli,cockpit-composer state=installed

    - name: "SETUP VIRTUALIZATION: service restart"
      service: name="cockpit.socket" state=restarted enabled=yes
      
    - name: "SETUP VIRTUALIZATION: firewall configuration"
      firewalld: port=9090/tcp permanent=yes immediate=yes state=enabled
 

