---
- hosts: node3.example.com
  tasks:
  
    - name: "SETUP BOOM: yum install packages"
      yum: name=boom-boot state=installed
      
    - name: "SETUP BOOM: cheat file installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-checkhost.j2', dest: '/usr/local/bin/cheat-boom-checkhost.sh'} 
        - {src: 'cheat-boom-lvcreate.j2', dest: '/usr/local/bin/cheat-boom-lvcreate.sh'} 
        - {src: 'cheat-boom-lvs.j2', dest: '/usr/local/bin/cheat-boom-lvs.sh'} 
        - {src: 'cheat-boom-addstorage.j2', dest: '/usr/local/bin/cheat-boom-addstorage.sh'} 
        - {src: 'cheat-boom-importantstuff.j2', dest: '/usr/local/bin/cheat-boom-importantstuff.sh'} 
        - {src: 'cheat-boom-grublist.j2', dest: '/usr/local/bin/cheat-boom-grublist.sh'} 
        
