---
- hosts: all
  tasks:
  
    - name: "PREP: TEMPLATE /etc/motd"
      template:
        src: motd-generic.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644  

    - name: "PREP: YUM remove UN-WANTED packages"
      yum: name=insights-client state=absent
      register: result
      retries: 10
      until: result is succeeded
      delay: 5

    - name: "PREP: YUM install WANTED packages"
      yum: name=tmux state=installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5

    - name: "PREP: FILE remove UN-WATNED motd messages"
      file:
        path: /etc/motd.d/cockpit
        state: absent

    - name: "PREP: SERVICE disable and stop unwanted services"
      service: 
        name="{{ item.name }}"
        state=stopped
        enabled=no
      with_items:
        - {name: 'rhsmcertd'}

    - name: "PREP: CMD disable yum plugins for subscription-manager"
      shell: 
        cmd: |          
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/subscription-manager.conf
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/product-id.conf
                    
    - name: "PREP: USER create and/or reset users"
      user: name="{{ item.name }}" password="{{ item.password }}"
      with_items:
        - {name: 'root', password: '$6$9Jk5EGiB2aBl95kj$RIdiSqNdKt95zqddStFUY/zVKIUujWfGWJkLM5KQ.7zY88Kxxa0qm78qLMFRAqDO2qOrp.qZBaQAKcUFm1Is70'}
        - {name: '{{ student_username }}', password: '$6$9Jk5EGiB2aBl95kj$RIdiSqNdKt95zqddStFUY/zVKIUujWfGWJkLM5KQ.7zY88Kxxa0qm78qLMFRAqDO2qOrp.qZBaQAKcUFm1Is70'}

    - name: "PREP: USER modification"
      user: name="{{ student_username }}" groups="wheel"

    - name: "PREP: Sudo Configuration"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0600
      with_items:
        - {src: 'sudoers.j2', dest: '/etc/sudoers.d/rhel8-workshop'}
        - {src: 'sudoers-student.j2', dest: '/etc/sudoers.d/{{ student_username }}'}

- import_playbook: rhel8-prep-sshkeys.yml
- import_playbook: rhel8-setup-wayland.yml
- import_playbook: rhel8-setup-appstreams.yml
- import_playbook: rhel8-setup-systemd.yml
- import_playbook: rhel8-setup-firewalld.yml
- import_playbook: rhel8-setup-nftables.yml
- import_playbook: rhel8-setup-ebpf.yml
- import_playbook: rhel8-setup-boom.yml
- import_playbook: rhel8-setup-podman.yml
- import_playbook: rhel8-setup-buildah.yml
- import_playbook: rhel8-setup-stratis.yml
- import_playbook: rhel8-setup-tlog.yml
- import_playbook: rhel8-setup-lvm-vdo.yml
- import_playbook: rhel8-setup-virtualization.yml
- import_playbook: rhel8-setup-kpatch.yml


## Save the webconsole for last since it will discconect webconsole session on service restart
- import_playbook: rhel8-setup-webconsole.yml
